name: eShopOnWeb Build and Deploy IIS

on:
  push:
    branches: [main, feature/*]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release

    - name: Publish
      run: dotnet publish ./src/Web/Web.csproj --no-build --configuration Release --property:PublishDir='./publish_output'

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish_output
        path: ./src/Web/publish_output

  IIS:
    runs-on: [self-hosted, IIS_POC]
    needs: Build
    environment: IIS
    steps:
    - name: Deploy to IIS
      run: |
        iisreset /stop
        Copy-Item ./publish_output/* C:/inetpub/wwwroot/SampleCRM -Recurse -Force
        iisreset /start